alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias http='python -m http.server'
alias xip='curl icanhazip.com'
alias ag='ag --path-to-agignore ~/.ignore'
alias reload='source ~/.bashrc'
alias se='sudoedit'
alias bashrc='vim ~/.bashrc'
alias vimrc='vim ~/.vimrc'
alias grep='grep --color=auto'
alias poweroff='sudo poweroff'
alias fan='sudo resume'
alias hib='pm-hibernate'
alias susp='pm-suspend'
alias mkdir='mkdir -pv'
alias ls='ls --color=always -F'
alias sl='ls'
alias l='ls'
alias ll='ls -Alh'
alias df='df -H'
alias vi='vim'
alias sudo='sudo '
alias locip="ip addr show | grep -E 'inet' | grep -m 1 global | cut -d\  -f6"
alias locksus="sudo ls && lock && sudo pm-suspend"
